/**
 * Mock seed data for Match — Commit 2.2 of the Mobile UI Quality Floor Redesign.
 * Industry pattern: social
 * Generated by packages/agents/src/app-generator/prompts/mobile-industry-seed-data.ts
 * Edit at the source — this file is regenerated on each build.
 */

import type { Match } from '@/types/entities';

export const matchs: Match[] = [
  {
    "_id": "2943d11c62c8af1063c8b0a3",
    "id": "2943d11c62c8af1063c8b0a3",
    "title": "Personal Match",
    "user1": "6c1a4938d997150cda97169f",
    "user2": "6c1a4938d997150cda97169f",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Personal Match"
  },
  {
    "_id": "2a43d2afc956f517c856f384",
    "id": "2a43d2afc956f517c856f384",
    "title": "Work Match",
    "user1": "6d1a4acb4160fc934060fb00",
    "user2": "6d1a4acb4160fc934060fb00",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Work Match"
  },
  {
    "_id": "2b43d4422d02c13e2e02c2d1",
    "id": "2b43d4422d02c13e2e02c2d1",
    "title": "Shared Match",
    "user1": "6e1a4c5ec3f8690ac4f86a9d",
    "user2": "6e1a4c5ec3f8690ac4f86a9d",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Shared Match"
  }
] as unknown as Match[];
