/**
 * Mock seed data for Swipe — Commit 2.2 of the Mobile UI Quality Floor Redesign.
 * Industry pattern: social
 * Generated by packages/agents/src/app-generator/prompts/mobile-industry-seed-data.ts
 * Edit at the source — this file is regenerated on each build.
 */

import type { Swipe } from '@/types/entities';

export const swipes: Swipe[] = [
  {
    "_id": "63d65e2b3be279733ae277e0",
    "id": "63d65e2b3be279733ae277e0",
    "title": "Personal Swipe",
    "profileSwiped": "6c1a4938d997150cda97169f",
    "action": "like",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Personal Swipe"
  },
  {
    "_id": "62d65c98d555c66cd655c7ff",
    "id": "62d65c98d555c66cd655c7ff",
    "title": "Work Swipe",
    "profileSwiped": "6d1a4acb4160fc934060fb00",
    "action": "pass",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Work Swipe"
  },
  {
    "_id": "65d6615136305ee935305d56",
    "id": "65d6615136305ee935305d56",
    "title": "Shared Swipe",
    "profileSwiped": "6e1a4c5ec3f8690ac4f86a9d",
    "action": "like",
    "createdAt": "2025-12-29T23:01:21Z",
    "updatedAt": "2025-12-29T23:01:21Z",
    "name": "Shared Swipe"
  }
] as unknown as Swipe[];
