// Rich sample data for Spectrum dating app
export const SAMPLE_PROFILES = [
  {
    _id: 'user_1',
    name: 'Sofia Reyes',
    title: 'Travel Photographer',
    bio: 'Chasing sunsets and good coffee ☕ | Based in NYC but always somewhere new | Looking for someone to explore the world with',
    age: 27,
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80',
      'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=800&q=80',
    ],
    location: 'New York, NY',
    distance: '2 miles away',
    interests: ['Photography', 'Travel', 'Coffee', 'Hiking', 'Art'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: true,
    lastActive: 'Just now',
    compatibility: 94,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_2',
    name: 'Marcus Chen',
    title: 'Architect & Weekend Chef',
    bio: 'Designing spaces by day, perfecting pasta recipes by night 🍝 | Dog dad to Luna | Lover of jazz and rooftop views',
    age: 31,
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80',
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80',
    ],
    location: 'Brooklyn, NY',
    distance: '5 miles away',
    interests: ['Cooking', 'Architecture', 'Jazz', 'Dogs', 'Wine'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: false,
    lastActive: '2h ago',
    compatibility: 88,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_3',
    name: 'Amara Osei',
    title: 'Yoga Instructor & Wellness Coach',
    bio: 'Living intentionally 🌿 | Morning runs, evening meditations | Plant-based foodie | Looking for genuine connection',
    age: 29,
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80',
    ],
    location: 'Manhattan, NY',
    distance: '1 mile away',
    interests: ['Yoga', 'Wellness', 'Cooking', 'Reading', 'Nature'],
    relationshipGoal: 'Serious relationship',
    isVerified: true,
    isOnline: true,
    lastActive: 'Just now',
    compatibility: 91,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_4',
    name: 'Liam Torres',
    title: 'Startup Founder & Surfer',
    bio: 'Building the future 🚀 | Catch me at the beach or a coffee shop | Passionate about tech, travel, and tacos 🌮',
    age: 33,
    photos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
      'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&q=80',
    ],
    location: 'Hoboken, NJ',
    distance: '8 miles away',
    interests: ['Surfing', 'Tech', 'Travel', 'Tacos', 'Startups'],
    relationshipGoal: 'Open to anything',
    isVerified: false,
    isOnline: true,
    lastActive: '15 min ago',
    compatibility: 79,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_5',
    name: 'Isabelle Fontaine',
    title: 'Art Director & Museum Lover',
    bio: 'Fluent in sarcasm and three languages 🎨 | Weekend museum marathons | Seeking someone who appreciates slow mornings',
    age: 28,
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
      'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=800&q=80',
      'https://images.unsplash.com/photo-1502767089025-6572583495b9?w=800&q=80',
    ],
    location: 'Upper West Side, NY',
    distance: '3 miles away',
    interests: ['Art', 'Museums', 'Languages', 'Film', 'Brunch'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: false,
    lastActive: '1h ago',
    compatibility: 86,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_6',
    name: 'Jordan Kim',
    title: 'Music Producer & Vinyl Collector',
    bio: 'Making beats and memories 🎵 | Record store regular | Looking for my concert buddy and life partner',
    age: 30,
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&q=80',
      'https://images.unsplash.com/photo-1488161628813-04466f872be2?w=800&q=80',
    ],
    location: 'Williamsburg, NY',
    distance: '6 miles away',
    interests: ['Music', 'Vinyl', 'Concerts', 'Nightlife', 'Fashion'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: true,
    lastActive: 'Just now',
    compatibility: 83,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_7',
    name: 'Priya Sharma',
    title: 'Pediatric Doctor & Bookworm',
    bio: 'Healing little hearts by day, lost in novels by night 📚 | Chai enthusiast | Believer in kindness and good conversation',
    age: 32,
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80',
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80',
    ],
    location: 'Queens, NY',
    distance: '12 miles away',
    interests: ['Reading', 'Medicine', 'Chai', 'Cooking', 'Volunteering'],
    relationshipGoal: 'Marriage-minded',
    isVerified: true,
    isOnline: false,
    lastActive: '3h ago',
    compatibility: 90,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_8',
    name: 'Ethan Brooks',
    title: 'Marine Biologist & Diver',
    bio: 'Ocean is my office 🌊 | Scuba diver, coral reef advocate | Looking for someone who loves adventure as much as I do',
    age: 34,
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&q=80',
      'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=800&q=80',
    ],
    location: 'Jersey City, NJ',
    distance: '9 miles away',
    interests: ['Diving', 'Ocean', 'Travel', 'Photography', 'Environment'],
    relationshipGoal: 'Long-term relationship',
    isVerified: false,
    isOnline: true,
    lastActive: '30 min ago',
    compatibility: 77,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_9',
    name: 'Zara Williams',
    title: 'Fashion Stylist & Podcast Host',
    bio: 'Style is a form of self-expression 👗 | Hosting "Real Talk" podcast | Dog mom | Brunch every Sunday, no exceptions',
    age: 26,
    photos: [
      'https://images.unsplash.com/photo-1526510747491-58f928ec870f?w=800&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80',
    ],
    location: 'SoHo, NY',
    distance: '4 miles away',
    interests: ['Fashion', 'Podcasting', 'Brunch', 'Dogs', 'Networking'],
    relationshipGoal: 'Open to anything',
    isVerified: true,
    isOnline: false,
    lastActive: '45 min ago',
    compatibility: 81,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_10',
    name: 'Noah Patel',
    title: 'Chef & Food Blogger',
    bio: 'Michelin-starred dreams, street food heart 🍜 | Food is love made visible | Let me cook for you sometime',
    age: 29,
    photos: [
      'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=800&q=80',
      'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=800&q=80',
    ],
    location: 'East Village, NY',
    distance: '2 miles away',
    interests: ['Cooking', 'Food', 'Travel', 'Wine', 'Blogging'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: true,
    lastActive: 'Just now',
    compatibility: 87,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_11',
    name: 'Luna Vasquez',
    title: 'Dancer & Choreographer',
    bio: 'Life is better when you dance 💃 | Contemporary & salsa | Teaching movement, learning life | Seeking my dance partner in crime',
    age: 25,
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
    ],
    location: 'Harlem, NY',
    distance: '7 miles away',
    interests: ['Dance', 'Music', 'Fitness', 'Travel', 'Art'],
    relationshipGoal: 'Serious relationship',
    isVerified: false,
    isOnline: true,
    lastActive: '5 min ago',
    compatibility: 85,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user_12',
    name: 'Alex Rivera',
    title: 'Filmmaker & Storyteller',
    bio: 'Every person has a story worth telling 🎬 | Sundance alumni | Coffee shop writer | Looking for my muse and partner',
    age: 35,
    photos: [
      'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=800&q=80',
      'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&q=80',
    ],
    location: 'Tribeca, NY',
    distance: '3 miles away',
    interests: ['Film', 'Writing', 'Coffee', 'Travel', 'Philosophy'],
    relationshipGoal: 'Long-term relationship',
    isVerified: true,
    isOnline: false,
    lastActive: '2h ago',
    compatibility: 89,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_STORIES = [
  { id: 'story_0', name: 'Your Story', isOwn: true, photo: null, isActive: false },
  { id: 'story_1', name: 'Sofia', photo: SAMPLE_PROFILES[0].photos[0], isActive: true, userId: 'user_1' },
  { id: 'story_2', name: 'Marcus', photo: SAMPLE_PROFILES[1].photos[0], isActive: false, userId: 'user_2' },
  { id: 'story_3', name: 'Amara', photo: SAMPLE_PROFILES[2].photos[0], isActive: true, userId: 'user_3' },
  { id: 'story_4', name: 'Liam', photo: SAMPLE_PROFILES[3].photos[0], isActive: true, userId: 'user_4' },
  { id: 'story_5', name: 'Isabelle', photo: SAMPLE_PROFILES[4].photos[0], isActive: false, userId: 'user_5' },
  { id: 'story_6', name: 'Jordan', photo: SAMPLE_PROFILES[5].photos[0], isActive: true, userId: 'user_6' },
  { id: 'story_7', name: 'Priya', photo: SAMPLE_PROFILES[6].photos[0], isActive: false, userId: 'user_7' },
];

export const SAMPLE_MATCHES = [
  {
    _id: 'match_1',
    title: 'Sofia & You',
    user1: 'current_user',
    user2: 'user_1',
    matchedUser: SAMPLE_PROFILES[0],
    lastMessage: 'Would love to grab coffee sometime! ☕',
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    unreadCount: 2,
    isNew: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'match_2',
    title: 'Amara & You',
    user1: 'current_user',
    user2: 'user_3',
    matchedUser: SAMPLE_PROFILES[2],
    lastMessage: 'That hiking trail sounds amazing!',
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    isNew: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'match_3',
    title: 'Jordan & You',
    user1: 'current_user',
    user2: 'user_6',
    matchedUser: SAMPLE_PROFILES[5],
    lastMessage: 'Check out this vinyl I just found 🎵',
    lastMessageTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    isNew: false,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'match_4',
    title: 'Priya & You',
    user1: 'current_user',
    user2: 'user_7',
    matchedUser: SAMPLE_PROFILES[6],
    lastMessage: 'I just finished that book you recommended!',
    lastMessageTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    isNew: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'match_5',
    title: 'Luna & You',
    user1: 'current_user',
    user2: 'user_11',
    matchedUser: SAMPLE_PROFILES[10],
    lastMessage: 'The salsa class was so fun! 💃',
    lastMessageTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 3,
    isNew: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_MESSAGES: Record<string, Array<{ id: string; text: string; senderId: string; timestamp: string; isRead: boolean }>> = {
  match_1: [
    { id: 'm1_1', text: 'Hey! I love your travel photos 📸', senderId: 'user_1', timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(), isRead: true },
    { id: 'm1_2', text: 'Thank you! Just got back from Lisbon last week', senderId: 'current_user', timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(), isRead: true },
    { id: 'm1_3', text: 'Oh wow, Lisbon is on my bucket list! How was it?', senderId: 'user_1', timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(), isRead: true },
    { id: 'm1_4', text: 'Would love to grab coffee sometime! ☕', senderId: 'user_1', timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(), isRead: false },
  ],
  match_2: [
    { id: 'm2_1', text: 'Your wellness content is so inspiring!', senderId: 'current_user', timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), isRead: true },
    { id: 'm2_2', text: 'That means so much, thank you! 🌿', senderId: 'user_3', timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(), isRead: true },
    { id: 'm2_3', text: 'That hiking trail sounds amazing!', senderId: 'user_3', timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), isRead: true },
  ],
};

export const SAMPLE_NOTIFICATIONS = [
  { id: 'notif_1', type: 'match', title: 'New Match! 🎉', message: 'You and Sofia both liked each other!', photo: SAMPLE_PROFILES[0].photos[0], time: '10 min ago', isRead: false },
  { id: 'notif_2', type: 'like', title: 'Someone liked you ❤️', message: 'A new admirer is waiting to be discovered', photo: SAMPLE_PROFILES[5].photos[0], time: '1h ago', isRead: false },
  { id: 'notif_3', type: 'message', title: 'New message from Amara', message: 'That hiking trail sounds amazing!', photo: SAMPLE_PROFILES[2].photos[0], time: '2h ago', isRead: true },
  { id: 'notif_4', type: 'match', title: 'New Match! 🎉', message: 'You and Luna both liked each other!', photo: SAMPLE_PROFILES[10].photos[0], time: '1 day ago', isRead: true },
  { id: 'notif_5', type: 'like', title: 'Someone super liked you ⭐', message: 'You made quite an impression!', photo: SAMPLE_PROFILES[3].photos[0], time: '2 days ago', isRead: true },
];
